id: P922DD696
initial_creation_type: ocr
source_metadata:
  volumes:
    10e0b1967f444683a011e0767b647e44:
      base_file: v106.txt
      image_group_id: I1PD95951
      title: གཏན་ཚིགས་ཀྱི་དེ་ཁོ་ན་ཉིད་བསྟན་པ།
      total_pages: 1054
      volume_number: 106
